####
#### The annotation description file for GOlr and AmiGO.
####
id: annotation_for_browser
schema_generating: false
description: Special schema for certain ontology browser widget\'s filters.
display_name: Annotations (BROWSER)
document_category: annotation
weight: -120
boost_weights: taxon_subset_closure_label^1.0 evidence_type_closure^1.0
result_weights: taxon_subset_closure_label^9.0 evidence_type_closure^8.0
filter_weights: taxon_subset_closure_label^9.0 evidence_type_closure^8.0
fields:
  - id: taxon
    description: "Taxonomic group."
    display_name: Organism
    type: string
    property: []
  - id: taxon_label
    description: "Taxonomic group and ancestral groups."
    display_name: Organism
    type: string
    property: []
    searchable: true
  - id: taxon_closure
    description: "Taxonomic group and ancestral groups."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
  - id: taxon_closure_label
    description: "Taxonomic group and ancestral groups."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: taxon_subset_closure
    description: "Taxonomic group (direct) and ancestral groups that are within the specified subset (e.g mammalia, eukaryota)."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
  - id: taxon_subset_closure_label
    description: "Labels for taxonomic group (direct) and ancestral groups that are within the specified subset."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: evidence_type
    description: "Evidence type."
    display_name: Evidence
    type: string
    property: []
  - id: evidence_type_closure
    description: "All evidence (evidence closure) for this annotation"
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []
