####
#### The annotation evidence aggregate description file for GOlr and
#### AmiGO.
####
id: bbop_ann_ev_agg
schema_generating: true
description: A description of annotation evidence aggregate for GOlr and AmiGO.
display_name: Advanced
document_category: annotation_evidence_aggregate
weight: -10
boost_weights: annotation_class^2.0 annotation_class_label^1.0 bioentity^2.0 bioentity_label^1.0 panther_family^1.0 panther_family_label^1.0 taxon_closure_label^1.0
result_weights: bioentity^4.0 annotation_class^3.0 taxon^2.0
filter_weights: evidence_type_closure^4.0 evidence_with^3.0 taxon_closure_label^2.0
fields:
  - id: id
    description: Gene/product ID.
    display_name: Acc
    type: string
    property: []
  - id: bioentity
    description: "Column 1 + columns 2."
    display_name: Gene/product ID
    type: string
    property: []
  - id: bioentity_label
    description: Column 3.
    display_name: Gene/product label
    type: string
    property: []
    searchable: true
  - id: annotation_class
    description: Column 5.
    display_name: Annotation class
    type: string
    property: []
  - id: annotation_class_label
    description: "Column 5 + ontology."
    display_name: Annotation class label
    type: string
    property: []
    searchable: true
  - id: evidence_type_closure
    description: All evidence for this term/gene product pair
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []
  - id: evidence_with
    description:  All column 8s for this term/gene product pair
    display_name: Evidence with
    type: string
    cardinality: multi
    property: []
  - id: taxon
    description: "Column 13: taxon."
    display_name: Taxon
    type: string
    property: []
  - id: taxon_label
    description: "Derived from C13 + ncbi_taxonomy.obo."
    display_name: Taxon
    type: string
    property: []
    searchable: true
  - id: taxon_closure
    description: "IDs derived from C13 + ncbi_taxonomy.obo."
    display_name: Taxon (IDs)
    type: string
    cardinality: multi
    property: []
  - id: taxon_closure_label
    description: "Labels derived from C13 + ncbi_taxonomy.obo."
    display_name: Taxon
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: panther_family
    description: Family IDs that are associated with this entity.
    display_name: Protein family
    type: string
    searchable: true
    property: []
  - id: panther_family_label
    description: Families that are associated with this entity.
    display_name: Family
    type: string
    searchable: true
    property: []
  # - id: phylo_graph
  #   description: JSON blob form of the phylogenic tree.
  #   display_name: This should not be displayed
  #   type: string
  #   property: []
  #   indexed: false
  ## TODO: Sleeping for now, but will re-add when the right
  ## experimental GAFs start getting loaded as well.
  # - id: phylo_ancestor_closure
  #   description: All ancestors of this entity.
  #   display_name: Phylogenic ancestors
  #   type: string
  #   cardinality: multi
  #   property: []
  # - id: phylo_descendant_closure
  #   description: All descendants of this entity.
  #   display_name: Phylogenic descendants
  #   type: string
  #   cardinality: multi
  #   property: []
