####
#### Get the environment setup. The assumed environment for this
#### category of applications.
####
---
###
### AmiGO config and setup.
###
## NPM install.
- name: npm install for amigo
  command: npm install
  args:
    chdir: /home/{{ remote_user }}/local/src/git/amigo/
## Get the right config in place.
- name: get amigo.yaml filled and in place
  template: src=../conf/examples/amigo.yaml.production dest=/home/{{ remote_user }}/local/src/git/conf/amigo.yaml
## NPM install.
- name: build for amigo
  command: ./node_modules/.bin/gulp install
  args:
    chdir: /home/{{ remote_user }}/local/src/git/amigo/
# - name: load for amigo
#   command: ./node_modules/.bin/gulp load-
#   args:
#     chdir: /home/{{ remote_user }}/local/src/git/amigo/
# - name: cache for amigo
#   command: ./node_modules/.bin/gulp cache
#   args:
#     chdir: /home/{{ remote_user }}/local/src/git/amigo/
