####
#### Use kwalify and this schema to validate the config files.
#### Examples:
####    kwalify -f ./scripts/schema.yaml ./metadata/ont-config.yaml
####    make check_metadata
####
type: map
mapping:
  "id":
    type: str
    required: yes
  "schema_generating":
    type: bool
    required: yes
  "description":
    type: str
    required: yes
  "display_name":
    type: str
    required: yes
  "document_category":
    type: str
    required: yes
  "weight":
    type: int
    required: no
  "boost_weights":
    type: str
    required: no
  "filter_weights":
    type: str
    required: no
  "result_weights":
    type: str
    required: no
  "fields":
    type: seq
    sequence:
      - type: map
        mapping:
          "id":
            type: str
            required: yes
          "description":
            type: str
            required: yes
          "display_name":
            type: str
            required: yes
          "type":
            type: str
            required: yes 
          "required":
            type: bool
            required: no
          "cardinality":
            type: str
            required: no
          # "property":
          #   type: str
          #   required: yes
          "property":
            type: seq
            required: yes
            sequence:
              - type: str
          "transform":
            type: seq
            required: no
            sequence:
              - type: str
          "searchable":
            type: bool
            required: no
          "indexed":
            type: bool
            required: no
